export const TransitData = [
    {
        id: 1,
        service_id: 12355,
        provider: "Cogent",
        circuit_id: 235,
        circuit_type: "Test Type",
        client_id: 3698,
        status: "Active",
        circuit_country: "America",
        circuit_city: "Amsterdam",
        port_capacity: "100 Mbps",
        bandwidth_commit: "100 Gbps",
        activation_date: "13-03-2021",
        expiration_date: "12-03-2022",
        metered_charge: "true",
        notes: "Test Note",
    },
    {
        id: 2,
        service_id: 12355,
        provider: "Cogent",
        circuit_id: 235,
        circuit_type: "Text Type",
        client_id: 3698,
        status: "Active",
        circuit_country: "America",
        circuit_city: "Amsterdam",
        port_capacity: "100 Mbps",
        bandwidth_commit: "100 Gbps",
        activation_date: "13-03-2021",
        expiration_date: "12-03-2022",
        metered_charge: "false",
        notes: "Test Note",
    },
    {
        id: 3,
        service_id: 12355,
        provider: "Cogent",
        circuit_id: 235,
        circuit_type: "Text Type",
        client_id: 3698,
        status: "Active",
        circuit_country: "America",
        circuit_city: "Amsterdam",
        port_capacity: "100 Mbps",
        bandwidth_commit: "100 Gbps",
        activation_date: "13-03-2021",
        expiration_date: "12-03-2022",
        metered_charge: "true",
        notes: "Test Note",
    },
    {
        id: 4,
        service_id: 12355,
        provider: "Cogent",
        circuit_id: 235,
        circuit_type: "Text Type",
        client_id: 3698,
        status: "Active",
        circuit_country: "America",
        circuit_city: "Amsterdam",
        port_capacity: "100 Mbps",
        bandwidth_commit: "100 Gbps",
        activation_date: "13-03-2021",
        expiration_date: "12-03-2022",
        metered_charge: "false",
        notes: "Test Note",
    },
    {
        id: 5,
        service_id: 12355,
        provider: "Cogent",
        circuit_id: 235,
        circuit_type: "Text Type",
        client_id: 3698,
        status: "Active",
        circuit_country: "America",
        circuit_city: "Amsterdam",
        port_capacity: "100 Mbps",
        bandwidth_commit: "100 Gbps",
        activation_date: "13-03-2021",
        expiration_date: "12-03-2022",
        metered_charge: "true",
        notes: "Test Note",
    }
]